### ISSUE TITLE
BUG: Fixing extra characters at the end of l command.

### ISSUE THREAD

**Issue by EpStR0M** [LiskHQ/lisk-build#1]
On my Linux Mint machine after 63c176bb973f4f99b27f83ef7cb16de126e29251 it fails to build with the following message:

`+ sed -i '' "s%#!/home/caldeireiro/Desktop/lisk-build/src/node-v0.12.9/compiled/bin/node%#\!.\/bin\/node%g" lisk-0.1.1-Linux-armv6l/lib/node_modules/npm/bin/npm-cli.js
sed: can't read s%#!/home/caldeireiro/Desktop/lisk-build/src/node-v0.12.9/compiled/bin/node%#\!.\/bin\/node%g: No such file or directory
Error executing command, exiting`

But it works using

`sed -i \"s%$(head -1 $NPM_CLI)%#\!.\/bin\/node%g\" $NPM_CLI`

**Comment by karmacoma** [comment]
Hello,

The commit https://github.com/LiskHQ/lisk-build/commit/63c176bb973f4f99b27f83ef7cb16de126e29251 you referenced was a temporary fix for sed on OS X.

I will fix it so that it works for all supported platforms. Thank you for noticing, much appreciated :+1:

**Comment by Felgrym** [comment]
Same error, same fix worked for me too. Just confirming. Running Ubuntu 14.04 i686
Thanks :)
