### ISSUE TITLE
Suggestion to deactivate the automatic reloading of lisk when config.json changes

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-build#107]
With the new 0.8.0 release and pm2, the lisk directory and also the file config.json is actively monitored. If a change is detected, lisk is reloaded automatically. This means also that lisk is reloaded automatically, everytime you modify (and save) config.json.

I think this is more a bug than a feature and should be deactivated because of the following reasons:

* it's against common practice and general usage in Linux world. Normally, whenever you change a configfile of a process or a service, you have to manually reload this service to read the new config file. You wouldn't expect the service to reload automatically everytime you save that config file, even when not finished.
* it could be dangerous (killing lisk) when the config file is beeing modified and temporarily saved, even when not modified correctly. Lisk will reload then and crash, because of a non-valid config file. Lisk will probably not restart then automatically when the config file is correct.

What do you think about it?

**Comment by Isabello** [comment]
You know im prepared to just disabled watch entirely. Its kind of a pain and doesn't add value to our application...
