### ISSUE TITLE
Homepage says "Cannot GET /" after a reboot

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-build#11]
Moved from: https://github.com/LiskHQ/lisk/issues/72

> In the logs I get:
> error error: could not connect to server: Connection refused
> After a bash lisk.sh restart It becomes available again and loads fine, It seems the postgre DB dont load in time after a reboot (tested on two different vps), so I added a "sleep x" seconds to crontab job and still testing...
> 
> EDIT: Adding a 3 seconds sleep mitigate the problem, after many many tries it get a refused connection on reboot but then it loads normally (Cannot GET appears for a second refreshing the page many times on loading)
> 
> EDIT2: Adding a 5 seconds pause delay I dont get problems.

Courtesy of: @metal494

**Comment by Isabello** [comment]
#13 the pull request mention should accomodate this issue

**Comment by gelinger777** [comment]
I still get the issue on very fresh installed lisk

**Comment by jazy510** [comment]
Try:
./lisk.sh coldstart
