### ISSUE TITLE
Signed and checksummed Lisk files

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-build#12]
From: https://github.com/LiskHQ/lisk/issues/53

> There should be a way for a delegate to check the integrity of the lisk core files and lisk itself before launching to prevent malicious modification of files and processes implemented in the client.

**Comment by mrv777** [comment]
I'm a novice with all of this and didn't test this, but could we do something like to check the files:

Make a checksum file of all the files in the lisk folder and host it on lisk.io:
`find ./ -type f -print0 | xargs -0 md5sum > lisk_checksums.md5`
Then on every lisk startup, run something like this and check for any warnings:
`md5sum -c https://downloads.lisk.io/lisk/test/0.2.1/lisk_checksums.md5`

**Comment by Isabello** [comment]
Current state this is addressed upon installing Lisk when the files are pulled down but not upon Lisk launch. Looking into a way to keep file integrity checked post installation when the process is cycled or started. Considering @mrv777 solution but would require individual .md5 lists for each OS to be kept and certain files excluded.

All of pgsql/data/
config.json
logs.log
app.log
app.pid
pgsql.log

**Comment by Isabello** [comment]
I did some more thinking on this. When you load a DAPP is anything in core lisk modified to accomodate the DAPP? This might be important to consider if we implement md5 summing most of the items in the installation.

**Comment by karmacoma** [comment]
@Isabello Dapps are installed into a subdirectory `dapps`. A `tmp` directory is used to download archives into before unarchiving and eventual disposal. Everything else happens in db. Contents of each dapp folder should remain unchanged after that.

**Comment by fix** [comment]
i think the dapp api should take care of its own way to verify integrity of the dapp folder
