### ISSUE TITLE
installLisk.sh improvements

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-build#124]
It would be lovely to implement:
- Self-updating of installLisk.sh while doing **upgrade**
- Displaying current version of script and maybe optionally latest available with optional update in case of other actions than **upgrade**
- Rename ? Not sure if it wouldn't be better simply change **installLisk.sh** to **lisk.sh**, I know name lisk.sh is used inside lisk dir, but imo installLisk.sh is a little bit too long and case sensitive.
- Rename **upgrade** to **update**, as far as i'm concerned upgrade is more commonly used regarding hardware while update more commonly for software.

*Self-update may be tricky but it can be done with creating and executing temporary helper script which will close current one, update and relaunch main one.

**Comment by Isabello** [comment]
1. Self update, maybe.
2. Yes I will do
3. I dont really want to change the name. Lots of documentation already uses this name.
4. Upgrade is the term we should use. More info: https://de.wikipedia.org/wiki/Upgrade

**Comment by Isabello** [comment]
Closing in favour of #195
