### ISSUE TITLE
Installation fails on ArchLinux with psql issues.

### ISSUE THREAD

**Issue by 4fryn** [LiskHQ/lisk-build#132]
I can't get lisk running on ArchLinux. Mainly it fails to create a postgresql user and database. This is what the script prints out:

     ~ $ bash installLisk.sh install -r test
    Checking prerequisites:
    curl is installed.          Passed
    Tar is installed.         Passed
    Wget is installed.          Passed
    Sudo is installed and authenticated.      Passed
    All preqrequisites passed!
    Where do you want to install Lisk to? (Default /home/lisk): 
    Would you like to synchronize from the Genesis Block? (Default no): 

    Downloading current Lisk binaries: lisk-Linux-x86_64.tar.gz
    ######################################################################## 100.0%

    Checksum Passed!

    Extracting Lisk binaries to /home/lisk/lisk-test

    Cleaning up downloaded files

    Coldstarting Lisk for the first time
    √ Postgresql started successfully.
    X Failed to create Postgresql user.

    Stopping Lisk to perform database tuning
    √ Lisk stopped successfully.
    √ Postgresql stopped successfully.

    Executing database tuning operation
    Updates completed

    Configuring Logrotate for Lisk

    Starting Lisk with official snapshot
    √ Lisk stopped successfully.
    √ Postgresql started successfully.
    X Failed to create Postgresql database.

Souldn't the script exit / abort after `X Failed to create Postgresql user.`? Because proceeding after this does not make any sense.

After checking why this fails, I noticed postgresql is not even intalled on my system. Shouldn't the script check that? Is psql installed by default on other distributions?

    Success. You can now start the database server using:

        /home/lisk/lisk-test/pgsql/bin/pg_ctl -D /home/lisk/lisk-test/pgsql/data -l logfile start

    server starting
    √ Postgresql started successfully.
    dropuser: could not connect to database postgres: FATAL:  the database system is starting up
    createuser: could not connect to database postgres: FATAL:  the database system is starting up
    psql: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
    X Failed to create Postgresql user.

The logs further suggest the database is still starting up. Why does it say that it is already started up? Ok, I see it only checks the exit status of the database, not the actual progress. Maybe there is a way to loop checking the database progress and only continue if it's really running?

I [tried increasing](https://github.com/4fryn/lisk-build/commit/f02822701761d99e38ce94e8d32cc22f2bee9759) the sleep delay to something like 15 seconds in [lisk.sh:165](https://github.com/LiskHQ/lisk-build/blob/development/scripts/lisk.sh#L165), but without success.

Further issue, is the missing `libreadline.so.6`, is there any custom psql provided with lisk which is linked against and outdated version of readline?

    0 ✓ lisk@dings ~ $ pacman -Qs readline
    local/readline 7.0.003-1
        GNU readline library
    0 ✓ lisk@dings ~ $ find /usr/lib | grep -i libreadline
    /usr/lib/libreadline.so.7.0
    /usr/lib/libreadline.so
    /usr/lib/libreadline.so.7

Sorry for merging so many issues into a single ticket, but it's all basically related. It would be nice to get this beast running on Arch since I use it everywhere from Laptop, Desktop to Server.

**Comment by Isabello** [comment]
Postgresql is bundled in the binaries.

Postgres requires libreadline6. If you don't have it you will need to
install it.

I can look at adding more error checking in the install but you will have
to resolve the libreadline6 issue. The platforms we support are Ubuntu and
RHEL based distros. Any other Linux platforms are not validated against.

**Comment by 4fryn** [comment]
> Postgres requires libreadline6. If you don't have it you will need to install it.

Postgres is working fine with libreadline7.

    0 ✓ lisk@dings ~ $ /home/lisk/lisk-test/pgsql/bin/psql --version
    /home/lisk/lisk-test/pgsql/bin/psql: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
    127 ✗ lisk@dings ~ $ /usr/bin/psql --version
    psql (PostgreSQL) 9.6.3

**Comment by Isabello** [comment]
Ok. I'll look into including libreadline6 in the binaries and linking
against libreadline7 for a future release.

**Comment by Isabello** [comment]
I have opened separate issues to track this particular problem and both courses of action.

**Comment by 4fryn** [comment]
Funny, I just found my own ticket via Google. Having exactly the same issue on Ubuntu 17.4.

	Checksum Passed!

	Extracting Lisk binaries to /home/lisk/lisk-main

	Cleaning up downloaded files

	Coldstarting Lisk for the first time
	√ Postgresql is running.
	X Failed to create Postgresql user.
	Installation failed. Cleaning up...

	Stopping Lisk components before cleanup
	√ Lisk stopped successfully.
	X Postgresql failed to stop.
	√ Postgresql Killed.

	Removing Lisk directory and installation files

	Please check installLisk.out for more details on the failure. See here for troubleshooting steps: https://docs.lisk.io/docs/core-troubleshooting

	If no steps resolve your issue, please log an issue at: https://github.com/LiskHQ/lisk-build/issues

There is no additional information in `installLisk.out` an the troubleshooting site says, there are _no problems reported_ :)

**Comment by 4fryn** [comment]
+ case $1 in
	+ coldstart_lisk
	+ stop_lisk
	+ stop_postgresql
	+ rm -rf /home/lisk/lisk-main/pgsql/data
	+ pg_ctl initdb -D /home/lisk/lisk-main/pgsql/data
	+ sleep 2
	+ start_postgresql
	+ pgrep -x postgres
	+ echo '√ Postgresql is running.'
	√ Postgresql is running.
	+ sleep 1
	+ create_user
	+ dropuser --if-exists lisk
	+ createuser --createdb lisk
	+ psql -qd postgres -c 'ALTER USER lisk WITH PASSWORD '\''password'\'';'
	+ echo 'X Failed to create Postgresql user.'
	X Failed to create Postgresql user.
	+ exit 1

Manually:

     ~ $ dropuser --if-exists lisk
    dropuser: removal of role "lisk" failed: ERROR:  permission denied to drop role
     ~ $ createuser --createdb lisk
    createuser: creation of new role failed: ERROR:  permission denied to create role

Any idea?
