### ISSUE TITLE
Sources archive unpacking error

### ISSUE THREAD

**Issue by densmirnov** [LiskHQ/lisk-build#14]
When running build.sh it produces an error, when trying to rename unpacked source folder.

`+ mv -f 0.2.1 lisk-0.2.1-FreeBSD-amd64`
`mv: rename 0.2.1 to lisk-0.2.1-FreeBSD-amd64: No such file or directory`
`Error executing command, exiting`

**Comment by Isabello** [comment]
I don't believe the pull request here is necessary. Explanation was left on the pull request #15
