### ISSUE TITLE
rpath error build 0.9.0 

### ISSUE THREAD

**Issue by Nerigal** [LiskHQ/lisk-build#153]
ERROR   0002: file '/opt/lisk/client/lib/libreadline.so.7.0' contains an invalid rpath '/usr/local/lib' in [/usr/local/lib]
ERROR   0002: file '/opt/lisk/client/lib/libhistory.so.7.0' contains an invalid rpath '/usr/local/lib' in [/usr/local/lib]

**Comment by Nerigal** [comment]
ERROR   0002: file '/opt/lisk/client/lib/libreadline.so.7.0' contains an invalid rpath '/usr/local/lib' in [/usr/local/lib]
ERROR   0002: file '/opt/lisk/client/lib/libhistory.so.7.0' contains an invalid rpath '/usr/local/lib' in [/usr/local/lib]

still present in 0.9.2a

**Comment by Isabello** [comment]
Will check it. Not sure why rpath removal failed on this build...
