### ISSUE TITLE
Refactor lisk.sh and port logic to nodejs

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-build#159]
Lisk.sh is an amalgamation of many components. To improve this, we should export as many of the functions to nodejs to allow for more thorough testing and provide more robust feature sets.

**Comment by simonmorgenthaler** [comment]
`./lisk.sh stop` does not stop/cleanup the pm2 instances. When doing a fresh install of Lisk using `lisk.sh stop`, there is the possibility that pm2 is still running in the background. After installing a new version, multiple pm2 instances are running.

**Comment by Isabello** [comment]
Closing this for now. Will open a new issue in the future to address the pieces that can be ported to node.
