### ISSUE TITLE
Remove support for lisk-node

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-build#160]
As a result of: https://github.com/LiskHQ/lisk/issues/560, `lisk-node` will no longer be used or maintained in its current form. Therefore we will remove support in Lisk Build/Core `1.0.0`.

**Comment by diego-G** [comment]
Commit https://github.com/LiskHQ/lisk/commit/c0a42ac1d64a35888668308a843e841792825d3b already removes lisk-node from core. This needs to be aligned in lisk-build.
