### ISSUE TITLE
Additional verbosity for lisk.sh

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-build#182]
> $ bash lisk.sh status
> √ Lisk is running as PID: 11250
> Current Block Height:  2876743
> It should also print out information about:

> - [ ]   node (ip, address, port, ssl, ...)
> - [ ]   network (testnet, main)
> - [ ]   health (connected peers, block number versus chain head)
> - [ ]   forging status (on, off, delegate)

From: https://github.com/LiskHQ/lisk/issues/692

**Comment by 4fryn** [comment]
Yeah, right :blush:

**Comment by Isabello** [comment]
I would argue against implementing all of these things in lisk.sh. That script is solely designed to manage node start and stop, and the database. Some of the information can be useful and I will implement the ones that make sense.

All of these things can be implemented in the purpose built tool that is up and coming, and its my preference for that to be the route taken instead of doing it all here.

**Comment by 4fryn** [comment]
I'm now in favor of closing this issue against lisk.sh with the upcoming changes in tools.

**Comment by Isabello** [comment]
Ahhh, well I feel pretty good about having this information display after node is started actually :) Maybe I can implement the usage of the new toolset to provide instead. I will leave this open for now to serve as a reminder to do that.
