### ISSUE TITLE
Failed to create Postgresql user.

### ISSUE THREAD

**Issue by ImSMAbdullah** [LiskHQ/lisk-build#197]
Failed to create Postgresql user. please help me to clarify. I'm using Ubuntu 16.4 through SSH. 

lisk@localhost:~$ wget https://downloads.lisk.io/lisk/test/installLisk.sh
--2017-09-26 12:01:45--  https://downloads.lisk.io/lisk/test/installLisk.sh
Resolving downloads.lisk.io (downloads.lisk.io)... 94.237.40.215
Connecting to downloads.lisk.io (downloads.lisk.io)|94.237.40.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13472 (13K) [application/octet-stream]
Saving to: ‘installLisk.sh.4’

installLisk.sh.4    100%[===================>]  13.16K  --.-KB/s    in 0s      

2017-09-26 12:01:45 (421 MB/s) - ‘installLisk.sh.4’ saved [13472/13472]

lisk@localhost:~$ bash installLisk.sh install -r test
Checking prerequisites:
curl is installed.					Passed
Tar is installed.					Passed
Wget is installed.					Passed
Sudo is installed.					Passed
Please provide sudo password for validation

Sudo authenticated.					Passed
All preqrequisites passed!
Where do you want to install Lisk to? (Default /home/lisk): 
Would you like to synchronize from the Genesis Block? (Default no): 
√ NTP is running

Downloading current Lisk binaries: lisk-Linux-x86_64.tar.gz
######################################################################## 100.0%

Checksum Passed!

Extracting Lisk binaries to /home/lisk/lisk-test

Cleaning up downloaded files

Coldstarting Lisk for the first time
√ Postgresql is running.
X Failed to create Postgresql user.
Installation failed. Cleaning up...

Stopping Lisk components before cleanup
√ Lisk stopped successfully.
X Postgresql failed to stop.
√ Postgresql Killed.

Removing Lisk directory and installation files

For your reference : [Binary - Test Network.pdf](https://github.com/LiskHQ/lisk-build/files/1333123/Binary.-.Test.Network.pdf)

**Comment by Isabello** [comment]
You already have postgres installed at the OS level. Closing this issue as its end user error. You can clearly see this when it says coldstarting and it says its already running, same with the failed to stop message.
