### ISSUE TITLE
Update lisk_snapshot.sh for latest Lisk release

### ISSUE THREAD

**Issue by biolypl** [LiskHQ/lisk-build#202]
I installed Lisk 0.9.9 with liskInstall.sh but seems lisk_snapshot.sh isn't updated, when I try to make snapshot (of course without 'c' parametr) I get this message:
 `Unimplemented option: -c`

**Comment by Isabello** [comment]
Closing this one as duplicate. In the future please provide more information and maybe some research. Duplicate of: #205
