### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by benjiqq** [LiskHQ/lisk-build#22]
I have a few issues with building on mac. I think installLisk.sh would need some adaption to be runnable on Mac.

```
./installLisk.sh: line 160: md5sum: command not found
Checksum Failed, aborting installation

Starting Lisk with all parameters in place
Error: forever command was not found. Aborting.
```

**Comment by Isabello** [comment]
I will do my best to fix this. I don't have a mac so it may be beneficial to have someone collaborate with me to fix the issues in the script.

**Comment by karmacoma** [comment]
I have a mac so will fix.

**Comment by fix** [comment]
closing it, there is the Darwin build on 0.3.2a https://downloads.lisk.io/lisk/test/0.3.2a/
