### ISSUE TITLE
installLinux.sh script will fail to run the command "nvm install v6.10.1"

### ISSUE THREAD

**Issue by yairlisk** [LiskHQ/lisk-build#225]
The `install_linux.sh` should check and install the system the packages that are needed to run lisk-build. The problem is that in `shared.sh` the definition for `cmd_exec` is running via `bash -c`
but `nvm` is not a command but bash function, hence it will not run from a bash script. We could run it without the `cmd_exec`.

### Expect behaviour
`nvm` should be installed to the correct version.

### Actual behaviour
Running the script results with the error:
```
bash: nvm: command not found
```

### Steps to reproduce
Start a fresh machine running linux:

```
git clone https://github.com/LiskHQ/lisk-build.git
cd toolchain/
chmod u+x install_linux.sh
./install_linux.sh
```

**Comment by ghost** [comment]
The whole `exec_cmd` construct does not make much sense to me; it could be replaced by `set -xe`.
See also [the Unofficial Bash Strict Mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/).

**Comment by karmacoma** [comment]
Fair point @fchavant 

Btw, we should update `nvm install v6.10.1` to `nvm install v6.12.2`

**Comment by karmacoma** [comment]
Works fine when you follow the provided instructions: `bash toolchain/install_linux.sh`

**Comment by karmacoma** [comment]
Ok I was wrong. Tried to install on a fresh server deployment and it does not work. We will fix as described.
