### ISSUE TITLE
Add support for ARMv8 builds

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-build#23]
Courtesy of MalReynolds:

> Hi - could you please do an ARMv8 build of the next version of Lisk to go along with the current ARMv6 and ARMv7 versions? I'd like to try Lisk on an ODROID C2, which is ARMv8....it has 2GHz quad processors, 2GB RAM, eMMC memory clocked at 120 Mbit/sec transfer time and gig ethernet clocked at 900 Mbit/sec transfer time. At $40 per unit, it could be a game changer for Lisk.

**Comment by fix** [comment]
What about this? Is this still a strategy to have DPoS running on small devices? IMHO this is antagonist ie, there is no point to run a full node if not a delegate, and there is no point to be a delegate if there is no powerful machines behind

**Comment by Isabello** [comment]
Arm support is being dropped for the time being, we should close this as `wontfix`
