### ISSUE TITLE
Forging after rebuild

### ISSUE THREAD

**Issue by SpaceGuildIntern** [LiskHQ/lisk-build#25]
With the new build of 0.3.1 forging won't start after a rebuild and needs a reload/restart to make the delegate forge again.

**Comment by Isabello** [comment]
This is standard functionality of reading the config.json file and the database being unpopulated. You will need to start forging via API or by UI if you are syncing from zero, or by reloading the process.

**Comment by karmacoma** [comment]
Please see: https://github.com/LiskHQ/lisk/issues/141 where we will look to implement a solution.
