### ISSUE TITLE
Lisk core testnet  installation failure

### ISSUE THREAD

**Issue by davewinters** [LiskHQ/lisk-build#252]
Hi,

When I attempt to install lisk core by following the build details hosted below:, i receive an error when the test node is starting for the first time due to the user postgresql not being created successfully.

I followed all the pre-requisites as documented here: 
https://lisk.io/documentation/core/pre-installation/binary-prerequisites

Installation link
https://lisk.io/documentation/core/installation/binary-test-network

Installation script output:
lisk@dw-laptop:~$ bash ./installLisk.sh install -r main
Checking prerequisites:
curl is installed.					Passed
Tar is installed.					Passed
Wget is installed.					Passed
Sudo is installed and authenticated.			Passed
All preqrequisites passed!
Where do you want to install Lisk to? (Default /home/lisk): 
Would you like to synchronize from the Genesis Block? (Default no): 
√ NTP is running

Downloading current Lisk binaries: lisk-Linux-x86_64.tar.gz
######################################################################## 100.0%

Checksum Passed!

Extracting Lisk binaries to /home/lisk/lisk-main

Cleaning up downloaded files

Coldstarting Lisk for the first time
√ Postgresql is running.
X Failed to create Postgresql user.
Installation failed. Cleaning up...

Stopping Lisk components before cleanup
√ Lisk stopped successfully.
X Postgresql failed to stop.
√ Postgresql Killed.

Removing Lisk directory and installation files

Please check installLisk.out for more details on the failure. See here for troubleshooting steps: https://docs.lisk.io/docs/core-troubleshooting

If no steps resolve your issue, please log an issue at: https://github.com/LiskHQ/lisk-build/issues
lisk@dw-laptop:~$ 
 
Do I need to create the postgresql user as a pre-requisite with a particular password or how do I overcome this error. I am on ubuntu 16.0.4

FYI: Awesome relaunch last night :) Looking forward working on the sdk in the coming future

Thanks,
David

**Comment by Saleh7** [comment]
https://github.com/LiskHQ/lisk-build/issues/248#issuecomment-353580025

**Comment by Nazgolze** [comment]
Hi David,

Are you running postgres as a system-wide service by any chance?
Lisk core bundles postgres with it and the two can be in conflict

Juan

**Comment by Nazgolze** [comment]
Hi @davewinters,

Are you running postgres as a system-wide service by any chance?
Lisk core bundles postgres with it and the two can be in conflict

Juan

**Comment by Nazgolze** [comment]
@davewinters 
If that's not it though ---  one thing that could cause this is not having the locale set
Can you post the output of "locale"

**Comment by Nazgolze** [comment]
Not enough info to proceed on this. Closing issue
