### ISSUE TITLE
rebuild_lisk stops in download_blockchain if blockchain.db exists

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-build#26]
gunzip asks for overwrite confirmation, but invisible because of -q option. Add -f?

**Comment by fix** [comment]
Do you mean the install script is not unzipping anymore the downloaded blockchain?

**Comment by ghost** [comment]
yes if blockchain.db is present it stops to ask if overwrite is ok. But you don't see the request because of -q option and/or redirect to &> /dev/null. I recommend to add -f option to force it to unzip without questions asked.

**Comment by Isabello** [comment]
I have resolved this in the next version of lisk.sh. #29
