### ISSUE TITLE
"Cannot GET /" error after fresh install of Lisk Core

### ISSUE THREAD

**Issue by irfanze** [LiskHQ/lisk-build#264]
Hi,
I have done a fresh install of lisk core following the binary installation document from lisk.io
Did not get any errors in the installation, but I am not able to get the API page. From the same system when i browse to http://localhost:8000. I get the error "Cannot GET /"

Kindly advise what needs to be done to resolve this.

**Comment by Nazgolze** [comment]
Hi @irfanze 
The old core web ui has been disabled for a few releases now. You should still be able to get to the api though.

Try going here and see if this works for you: http://localhost:8000/api/loader/status/ping

**Comment by irfanze** [comment]
Hi @Nazgolze 
I tried this link "http://localhost:8000/api/loader/status/ping" and I got the reply as "success:false".

**Comment by Nazgolze** [comment]
@irfanze that looks good (http://localhost:8080/documentation/api-reference/lisk-api-0-9/loader).
Looks like you're in a good spot to start using the api.

I'm going to close this issue. If you have any api questions though, we're on gitter and the community there is pretty active as well - https://gitter.im/LiskHQ/lisk
There's also https://lisk.chat
