### ISSUE TITLE
Remove redundant copying of libpq.* to /usr/lib

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-build#265]
In Lisk Core `1.0.0` we no longer depend on `pg-native`.

We therefore do not need to perform the following hack used to in the linking process when building our packages.

https://github.com/LiskHQ/lisk-build/blob/068c604a6e231712b3074ec8c5939c8ea02d62aa/build.sh#L151-L152

It should be removed.

**Comment by Nazgolze** [comment]
Closed by #266
