### ISSUE TITLE
Snapshot config - change to how this gets included

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-build#277]
Will generate this based off of the default config instead of maintaining 2 config copies

Needs to be done for both 0.9.x and 1.0.x

**Comment by nazarhussain** [comment]
@Nazgolze Do you mean to use same `config.json` from core instead of having seperate `snapshot.json` file? Yes I believe it will be work, but we need to compare both files to see any significant config changes.

**Comment by ghost** [comment]
I believe the following need to be changed:
- port
- logFileName
- db.database
- loading.loadPerIteration

Additionally those options should be changed to prevent unexpected issues:
- version
- minVersion
- peers.list (empty)

**Comment by diego-G** [comment]
Please, prioritise this issue. Thanks

**Comment by Nazgolze** [comment]
Closed by #279

**Comment by ghost** [comment]
We need to ensure `.fileLogLevel` is at least `info` (not the case with betanet for instance)

**Comment by Nazgolze** [comment]
Closed by #281
