### ISSUE TITLE
lisk-build on Debian Jessie

### ISSUE THREAD

**Issue by charmisuk** [LiskHQ/lisk-build#28]
bash build.sh does not work for me.

I searched for some time, but i don't know what the problem is yet. Postgresql has not been installed.

I will post the last 50ish lines before the error.

postgresql-9.5.2/doc/src/sgml/test-decoding.sgml
postgresql-9.5.2/doc/src/sgml/diskusage.sgml
postgresql-9.5.2/doc/src/sgml/spi.sgml
postgresql-9.5.2/doc/src/sgml/user-manag.sgml
postgresql-9.5.2/doc/src/sgml/storage.sgml
postgresql-9.5.2/doc/src/sgml/mk_feature_tables.pl
postgresql-9.5.2/doc/src/sgml/intro.sgml
postgresql-9.5.2/doc/src/sgml/gist.sgml
postgresql-9.5.2/doc/src/sgml/release-8.3.sgml
postgresql-9.5.2/doc/src/sgml/pgstattuple.sgml
postgresql-9.5.2/doc/src/sgml/uuid-ossp.sgml
postgresql-9.5.2/doc/src/sgml/start.sgml
postgresql-9.5.2/doc/src/sgml/planstats.sgml
postgresql-9.5.2/doc/src/sgml/nls.sgml
postgresql-9.5.2/doc/src/sgml/stylesheet.css
postgresql-9.5.2/doc/src/sgml/contacts.sgml
postgresql-9.5.2/doc/src/sgml/sslinfo.sgml
postgresql-9.5.2/doc/src/sgml/json.sgml
postgresql-9.5.2/doc/src/sgml/intarray.sgml
postgresql-9.5.2/doc/src/sgml/pgbuffercache.sgml
postgresql-9.5.2/doc/src/sgml/dblink.sgml
postgresql-9.5.2/doc/src/sgml/pgtrgm.sgml
postgresql-9.5.2/doc/src/sgml/xindex.sgml
postgresql-9.5.2/doc/src/sgml/sources.sgml
postgresql-9.5.2/doc/src/sgml/Makefile
postgresql-9.5.2/doc/src/sgml/earthdistance.sgml
postgresql-9.5.2/doc/src/sgml/release-8.2.sgml
postgresql-9.5.2/doc/src/sgml/tcn.sgml
postgresql-9.5.2/doc/src/sgml/information_schema.sgml
postgresql-9.5.2/doc/src/sgml/catalogs.sgml
postgresql-9.5.2/doc/src/sgml/auth-delay.sgml
postgresql-9.5.2/doc/src/sgml/tablefunc.sgml
postgresql-9.5.2/doc/src/sgml/pgrowlocks.sgml
postgresql-9.5.2/doc/src/sgml/tablesample-method.sgml
postgresql-9.5.2/doc/src/sgml/lobj.sgml
postgresql-9.5.2/doc/src/sgml/dfunc.sgml
postgresql-9.5.2/doc/src/sgml/ddl.sgml
postgresql-9.5.2/doc/src/sgml/pltcl.sgml
postgresql-9.5.2/doc/src/sgml/event-trigger.sgml
postgresql-9.5.2/doc/src/sgml/biblio.sgml
postgresql-9.5.2/doc/src/sgml/release-old.sgml
postgresql-9.5.2/doc/src/sgml/hstore.sgml
postgresql-9.5.2/doc/src/sgml/protocol.sgml
postgresql-9.5.2/doc/src/sgml/libpq.sgml
postgresql-9.5.2/doc/src/sgml/btree-gist.sgml
postgresql-9.5.2/doc/src/sgml/gin.sgml
postgresql-9.5.2/doc/src/sgml/auto-explain.sgml
postgresql-9.5.2/doc/src/sgml/monitoring.sgml
postgresql-9.5.2/doc/src/sgml/sourcerepo.sgml
postgresql-9.5.2/doc/src/sgml/passwordcheck.sgml
postgresql-9.5.2/doc/src/sgml/wal.sgml
postgresql-9.5.2/doc/src/sgml/pgcrypto.sgml
postgresql-9.5.2/doc/src/sgml/maintenance.sgml
postgresql-9.5.2/doc/src/sgml/fuzzystrmatch.sgml
postgresql-9.5.2/doc/src/sgml/keywords.sgml
postgresql-9.5.2/doc/src/sgml/recovery-config.sgml
postgresql-9.5.2/doc/src/sgml/lo.sgml
postgresql-9.5.2/doc/src/sgml/syntax.sgml
postgresql-9.5.2/doc/src/sgml/geqo.sgml
postgresql-9.5.2/doc/src/sgml/release-9.2.sgml
postgresql-9.5.2/doc/src/sgml/datetime.sgml
postgresql-9.5.2/doc/src/sgml/xml2.sgml
postgresql-9.5.2/doc/src/sgml/release-8.0.sgml
postgresql-9.5.2/doc/src/sgml/chkpass.sgml
postgresql-9.5.2/doc/src/sgml/release-8.4.sgml
postgresql-9.5.2/doc/src/sgml/dml.sgml
postgresql-9.5.2/doc/src/sgml/xfunc.sgml
postgresql-9.5.2/doc/src/sgml/release-8.1.sgml
postgresql-9.5.2/doc/src/sgml/plhandler.sgml
postgresql-9.5.2/doc/src/sgml/rangetypes.sgml
postgresql-9.5.2/doc/src/sgml/logicaldecoding.sgml
postgresql-9.5.2/doc/src/sgml/replication-origins.sgml
postgresql-9.5.2/doc/src/sgml/release.sgml
postgresql-9.5.2/doc/src/sgml/jadetex.cfg
postgresql-9.5.2/doc/src/sgml/perform.sgml
postgresql-9.5.2/doc/src/sgml/acronyms.sgml
postgresql-9.5.2/doc/src/sgml/rules.sgml
postgresql-9.5.2/doc/src/sgml/btree-gin.sgml
postgresql-9.5.2/doc/src/sgml/high-availability.sgml
postgresql-9.5.2/doc/src/sgml/textsearch.sgml
postgresql-9.5.2/doc/src/sgml/features.sgml
postgresql-9.5.2/doc/src/sgml/html-stamp
postgresql-9.5.2/doc/src/sgml/ltree.sgml
postgresql-9.5.2/doc/src/sgml/trigger.sgml
postgresql-9.5.2/doc/src/sgml/seg.sgml
postgresql-9.5.2/doc/src/sgml/client-auth.sgml
postgresql-9.5.2/doc/src/sgml/postgres.sgml
postgresql-9.5.2/doc/src/sgml/func.sgml
postgresql-9.5.2/doc/src/sgml/tsm-system-time.sgml
postgresql-9.5.2/doc/src/sgml/plpgsql.sgml
postgresql-9.5.2/doc/src/sgml/sql.sgml
postgresql-9.5.2/doc/src/sgml/README.links
postgresql-9.5.2/doc/src/sgml/tsearch2.sgml
postgresql-9.5.2/doc/src/sgml/pgstatstatements.sgml
postgresql-9.5.2/doc/src/sgml/xaggr.sgml
postgresql-9.5.2/doc/src/sgml/stylesheet.xsl
postgresql-9.5.2/doc/src/sgml/contrib.sgml
postgresql-9.5.2/doc/src/sgml/man-stamp
postgresql-9.5.2/doc/src/sgml/bki.sgml
postgresql-9.5.2/doc/src/sgml/unaccent.sgml
postgresql-9.5.2/doc/src/sgml/release-7.4.sgml
postgresql-9.5.2/doc/src/sgml/external-projects.sgml
postgresql-9.5.2/doc/src/sgml/problems.sgml
postgresql-9.5.2/doc/src/sgml/arch-dev.sgml
postgresql-9.5.2/doc/src/sgml/pageinspect.sgml
postgresql-9.5.2/doc/src/sgml/info.sgml
postgresql-9.5.2/doc/src/sgml/installation.sgml
postgresql-9.5.2/doc/src/sgml/xplang.sgml
postgresql-9.5.2/doc/src/Makefile
postgresql-9.5.2/doc/KNOWN_BUGS
postgresql-9.5.2/doc/Makefile
postgresql-9.5.2/doc/TODO
postgresql-9.5.2/doc/MISSING_FEATURES
postgresql-9.5.2/doc/bug.template
postgresql-9.5.2/HISTORY
postgresql-9.5.2/Makefile
postgresql-9.5.2/README
postgresql-9.5.2/COPYRIGHT
postgresql-9.5.2/GNUmakefile.in
postgresql-9.5.2/.gitattributes
postgresql-9.5.2/aclocal.m4
postgresql-9.5.2/configure.in
postgresql-9.5.2/INSTALL
- ./configure --prefix=/home/neo/lisk-build/src/postgresql-9.5.2/pgsql --host=arm-linux --without-readline --without-zlib --disable-spinlocks
  checking build system type... armv7l-unknown-linux-gnueabihf
  checking host system type... arm-unknown-linux-gnu
  checking which template to use... linux
  checking whether to build with 64-bit integer date/time support... yes
  checking whether NLS is wanted... no
  checking for default port number... 5432
  checking for block size... 8kB
  checking for segment size... 1GB
  checking for WAL block size... 8kB
  checking for WAL segment size... 16MB
  checking for arm-linux-gcc... arm-linux-gnueabihf-gcc
  checking whether the C compiler works... no
  configure: error: in `/home/neo/lisk-build/src/postgresql-9.5.2':
  configure: error: C compiler cannot create executables
  See`config.log' for more details
  Error executing command, exiting

and FYI
uname -a
Linux bitcoinuser 3.10.77 #7393 SMP Thu Jun 2 19:48:22 CST 2016 armv7l GNU/Linux

It is synology DS-715

**Comment by charmisuk** [comment]
This is last portion of config.log

  GNU nano 2.2.6               File: /home/neo/lisk-build/src/postgresql-9.5.2/config.log                                    

with_zlib='no'

## -----------

## confdefs.h.

## -----------

/\* confdefs.h */
#define PACKAGE_NAME "PostgreSQL"
#define PACKAGE_TARNAME "postgresql"
#define PACKAGE_VERSION "9.5.2"
#define PACKAGE_STRING "PostgreSQL 9.5.2"
#define PACKAGE_BUGREPORT "pgsql-bugs@postgresql.org"
#define PACKAGE_URL ""
#define PG_MAJORVERSION "9.5"
#define PG_VERSION "9.5.2"
#define USE_INTEGER_DATETIMES 1
#define DEF_PGPORT 5432
#define DEF_PGPORT_STR "5432"
#define BLCKSZ 8192
#define RELSEG_SIZE 131072
#define XLOG_BLCKSZ 8192
#define XLOG_SEG_SIZE (16 \* 1024 \* 1024)

configure: exit 77

**Comment by fix** [comment]
ok it seems posgresql does not handle armv7 architecture because he does not find a "good" C compiler: 
`arm-linux-gnueabihf-gcc checking whether the C compiler works... no`

I would need the full config.log on pastebin.

also see http://stackoverflow.com/questions/16188228/arm-compiler-with-autoconf

**Comment by karmacoma** [comment]
To cross-compile for ARM you need to install the compiler toolchain using the following command:

```
bash toolchains/install_rpi.sh
```

Then

```
bash build.sh armv7l
```
