### ISSUE TITLE
Bundle correct version of lisky / lisk-commander with 1.x releases

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-build#291]
Betanet releases have been shipped with lisky 0.3.0 which is not compatible with the 1.0 API.

**Comment by ghost** [comment]
@shuse2 said to use `lisk-commander@beta`

**Comment by Nazgolze** [comment]
Closed by #293

**Comment by ghost** [comment]
> lisk-commander 1.0.0-rc.0 is released on npm, please this version to bundle
> it can be installed by `npm i -g --production lisk-commander@1.0.0-rc.0` or  `npm i -g --production lisk-commander@next`

**Comment by ghost** [comment]
The binary was renamed from`lisky` to `lisk`; the question is whether the top-level symlink can be removed. @Nazgolze @karmacoma
