### ISSUE TITLE
Use network specific configuration during build

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-build#292]
With the change https://github.com/LiskHQ/lisk/issues/398 when PR https://github.com/LiskHQ/lisk/pull/2149 will be merged. We will be manage configurations of all networks under one directory and same branch. So during build process we need to decide should we keep all config in build or only specific to network we are building.

**Comment by ghost** [comment]
The easiest solution might to set `LISK_NETWORK` in `env.sh` at build time.

**Comment by Nazgolze** [comment]
I agree with @fchavant

**Comment by Nazgolze** [comment]
Closed by #301
