### ISSUE TITLE
Remove pgcrypto module

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-build#296]
We don't need that extension anymore as is not used.
https://github.com/LiskHQ/lisk-build/blob/9b8f9f5b677ff45484378d47a0e7115e9ff08930/build.sh#L109-L112

**Comment by 4miners** [comment]
Please hold with this.

**Comment by ghost** [comment]
We do not build PostgreSQL ourselves any more and pgcrypt comes at no extra cost to us.
