### ISSUE TITLE
Update snapshot configuration for 1.1

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-build#310]
snapshot configuration was previously generated based on config.json, which is now split up. This needs to be updated; `minVersion` cannot be set any more (this was very much optional, see #298).

See https://github.com/LiskHQ/lisk-scripts/issues/148

**Comment by fchavant** [comment]
Something like https://github.com/LiskHQ/lisk-scripts/pull/116/files is needed

**Comment by Nazgolze** [comment]
Closed by #330
