### ISSUE TITLE
Archive lisk-build repository

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-build#329]
Archive lisk-build repository when https://github.com/LiskHQ/lisk/issues/2400 is completed and builds made with the Makefile are live on testnet and mainnet

**Comment by ghost** [comment]
https://github.com/LiskHQ/lisk/pull/2545 has been merged and https://github.com/LiskHQ/lisk/issues/2400 has been closed; we still need to wait for 1.4 to be deployed to mainnet.

**Comment by ghost** [comment]
Lisk Core 1.4.0 has been deployed to mainnet.
@karmacoma this repository can be archived.
