### ISSUE TITLE
lisk_snapshot.sh not working on v0.4.0a

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk-build#39]
The following line in the script stall:

bash lisk.sh snapshot -s highest -c $SNAPSHOT_CONFIG

The highest word look unsupported.

On-screen output is:

Beginning snapshot verification process at Wed Sep 14 22:50:23 EDT 2016
Snapshot flag must be a number and greater than 0

Clearly related to (now closed) issue:

https://github.com/LiskHQ/lisk/issues/258

So I don't know first one that will be fixed...

**Comment by Gr33nDrag0n69** [comment]
I put this for now (legacy patch) and it work. (currently testing)

bash lisk.sh snapshot -s 100000 -c $SNAPSHOT_CONFIG

**Comment by Isabello** [comment]
I will adjust the logic
