### ISSUE TITLE
Bug: -r parameter not working in lisk_snapshot.sh

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk-build#43]
New round of test on v0.4.0b for snapshot feature found most issue solved.
But one ...
# Test 1

`bash /opt/lisk/client/lisk_snapshot.sh -t /opt/lisk/client/snapshot.json -s /opt/lisk/client/config.json -b /opt/lisk/backup -d 3 -r 10`
- -r 10 didn't worked, it used highest round
# Test 2

`bash lisk.sh snapshot -s 10 -c snapshot.json`
- -s 10 worked

**Comment by Isabello** [comment]
Resolved by commit https://github.com/LiskHQ/lisk-build/commit/8d0c04860d3aa20321079cf5208f8ee4401130b0
