### ISSUE TITLE
Block height is sometimes returned as empty

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-build#46]
Sometimes the `lisk.sh` script fails to get the block height and is returned as empty.

We should try to improve its reliability, and also gracefully handle the empty height like so: `Current Block Height: Unavailable`.

**Comment by Isabello** [comment]
This was addressed by commit https://github.com/LiskHQ/lisk-build/commit/9b473acd4a35ddec17f20625a2dc81b0718a0fa3
