### ISSUE TITLE
Add support for other Linux distributions (other than Debian/Ubuntu)

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk-build#5]
The installation script is not taking into consideration that database can be installed just on Ubuntu like distro and not CentOS/Fedora/Redhat. 
The script should be able to detect based on output of "lsb_release -i" if is running on the right distro.

Thank you.
@wannabe

**Comment by karmacoma** [comment]
@cezarsn Version 0.2.1 will ship with it's own postgresql, thus negating the need to install postgresql on a system wide basis. I've tested the binaries on Debian/Ubuntu/CentOS/Fedora. All working good.
