### ISSUE TITLE
defaultLiskLocation

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-build#56]
`"Where do you want to install Lisk to? (Default $defaultLiskLocation):"`

I think this should be current path where installLisk.sh is by default.

**Comment by Isabello** [comment]
this is not really needed. if users are following the documentation they will be installing to that same directory as `installLisk.sh`.

the installation script is designed to be used together with the documentation. advanced users can handle typing in a path.

**Comment by ghost** [comment]
In most cases it's not needed, but in some it is. it's not convenient to copy path multiple times. After once navigating to desired directory and downloading ` installLisk.sh` why do i need to provide path again, it's not convenient.
It's in case user wants to install it on different volume etc.
