### ISSUE TITLE
Can't run on FreeBSD 10

### ISSUE THREAD

**Issue by densmirnov** [LiskHQ/lisk-build#60]
On FreeBSD even when you install all packages without any errors you can't run Lisk itself because of the following error:

```
/usr/home/lisk/lisk-main/node_modules/sodium/build/Release/sodium.node: Undefined symbol "sodium_init"
error: Forever detected script exited with code: 1
```

**Comment by karmacoma** [comment]
@densmirnov Thanks for letting us know. There seems to be a problem with either `libsodium` or `node-sodium` on FreeBSD.  We will withdraw current the FreeBSD packages for `0.5.1` until we find a solution. Sorry for the inconvenience.

**Comment by Isabello** [comment]
For the time being we are dropping freebsd support. I recommend closing this and labeling it as `wontfix`
